### ISSUE TITLE
数据集-会话序列裁剪

### ISSUE THREAD

**Issue by WangZesheng12** [Zhang-xiaokun/DIDN#1]
同学你好，在 dataset.py 中，在使用 maxlen 对会话序列进行裁剪时，代码中写的是 new_train_set_x.append(x[:maxlen])，注释为 “# choose first 19 clicks in the sequence”，为什么是选择前 19 个，而不是 最后 19 个，label 为用户的最后一个交互，是在处理的时候像 GCE-GNN 那样对会话序列做了逆序吗？

**Comment by WangZesheng12** [comment]
同学你好，还有一个问题，我在点击 readme 连接下载了 yoochoose1_64后，发现数据样本为 3 元组，应该分别为 session seq, label, collaborative sessions，请问是如何生成 collaborative sessions 的？而且我观察到每条样本的 collaborative sessions 数量不同；请问 test.txt 中的 collaborative sessions 只来源于训练集吗？感谢回答！🙏

**Comment by Zhang-xiaokun** [comment]
首先感谢关注我们的工作！
  第一个问题：好问题！
  这个代码是参考NARM的，所用baselines中处理方法大都是这个，为了保持一致，我们的论文中也采用的这个。我在公开的代码中也链接了参考的地址Reference: https://github.com/lijingsdu/sessionRec_NARM/blob/master/data_process.py
  第二个问题：
  collaborative sessions 是按照cosine 相似度计算的，取的recent sessions中 top-k相似度的，recent sessions来自于同一个batch中的sessions。具体的你可以再看看论文和代码。

**Comment by Rececology** [comment]
好的，**感谢回复！**请问有 CoSAN 模型的代码链接或者实现吗？我在 paperswithcode 和 github 上都找不到

**Comment by WangZesheng12** [comment]
好的，感谢回复！请问有 20‘ CoSAN 模型的代码链接或者实现吗？我在 paperswithcode 和 github 上都找不到。
